//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ched.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DescriptionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ched.Localization.DescriptionStrings", typeof(DescriptionStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   重なっている判定が左端の位置に加え、ノーツの長さも条件になります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccurateOverlapDetection {
            get {
                return ResourceManager.GetString("AccurateOverlapDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重なっている判定が左端の位置に加え、ノーツのチャンネルも条件になります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AccurateOverlapDetection2 {
            get {
                return ResourceManager.GetString("AccurateOverlapDetection2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このノーツによって生成されるノーツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GenerateByThisNote {
            get {
                return ResourceManager.GetString("GenerateByThisNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOn {
            get {
                return ResourceManager.GetString("isOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DAMAGEと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnDamage {
            get {
                return ResourceManager.GetString("isOnDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DAMAGE2と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnDamage2 {
            get {
                return ResourceManager.GetString("isOnDamage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下向きAIRと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnDownAir {
            get {
                return ResourceManager.GetString("isOnDownAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExTAPと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnExTap {
            get {
                return ResourceManager.GetString("isOnExTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExTAP2と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnExTap2 {
            get {
                return ResourceManager.GetString("isOnExTap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLICKと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnFlick {
            get {
                return ResourceManager.GetString("isOnFlick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLICK2と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnFlick2 {
            get {
                return ResourceManager.GetString("isOnFlick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイドと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnGuide {
            get {
                return ResourceManager.GetString("isOnGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイド終点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnGuideEnd {
            get {
                return ResourceManager.GetString("isOnGuideEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイド始点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnGuideStart {
            get {
                return ResourceManager.GetString("isOnGuideStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ガイド中継点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnGuideStep {
            get {
                return ResourceManager.GetString("isOnGuideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   他のノーツと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnNotes {
            get {
                return ResourceManager.GetString("isOnNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライドと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnSlide {
            get {
                return ResourceManager.GetString("isOnSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド終点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnSlideEnd {
            get {
                return ResourceManager.GetString("isOnSlideEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド始点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnSlideStart {
            get {
                return ResourceManager.GetString("isOnSlideStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スライド中継点と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnSlideStep {
            get {
                return ResourceManager.GetString("isOnSlideStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAPと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnTap {
            get {
                return ResourceManager.GetString("isOnTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAP2と重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnTap2 {
            get {
                return ResourceManager.GetString("isOnTap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上向きAIRと重なった時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOnUpAir {
            get {
                return ResourceManager.GetString("isOnUpAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とこのノーツが重なっていれば に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string isOverlap {
            get {
                return ResourceManager.GetString("isOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されたノーツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecifiedNotes {
            get {
                return ResourceManager.GetString("SpecifiedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このノーツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Thisnote {
            get {
                return ResourceManager.GetString("Thisnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   をフリックにする に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToFlick {
            get {
                return ResourceManager.GetString("ToFlick", resourceCulture);
            }
        }
    }
}
